/**
 * Client-side news feed loader.
 * Reads /news-feed.json (generated by scripts/fetch-news.mjs).
 */

const FEED_URL = "/news-feed.json";
const CACHE_KEY = "cb_news_feed_v2";
const CACHE_TTL_MS = 30 * 60 * 1000;

/** Primary region tabs — India vs World */
export const NEWS_REGIONS = [
  { id: "all", label: "All", emoji: null },
  { id: "india", label: "India", emoji: "🇮🇳" },
  { id: "world", label: "World", emoji: "🌍" },
];

/** Topic filters (secondary) */
export const NEWS_FILTERS = [
  { id: "all-topics", label: "All topics" },
  { id: "verra", label: "Verra" },
  { id: "registry", label: "VCS Registry" },
  { id: "esg", label: "ESG / GHG" },
  { id: "green-hydrogen", label: "Green H₂" },
];

export function formatNewsDate(iso) {
  if (!iso) return "";
  try {
    return new Date(iso).toLocaleDateString("en-IN", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch {
    return iso;
  }
}

export function getArticlesByRegion(feed, regionId) {
  if (!feed?.articles) return [];
  if (regionId === "india") return feed.sections?.india || feed.articles.filter((a) => a.region === "india");
  if (regionId === "world") return feed.sections?.world || feed.articles.filter((a) => a.region === "world");
  return feed.articles;
}

export function filterArticles(articles, filterId) {
  if (!filterId || filterId === "all-topics") return articles;
  return articles.filter((a) => {
    switch (filterId) {
      case "verra":
        return a.source === "verra" || a.tag === "VERRA";
      case "registry":
        return a.source === "verra-registry" || a.type === "registry";
      case "esg":
        return a.type === "esg" || ["ESG", "CLIMATE", "CARBON MARKET"].includes(a.tag);
      case "green-hydrogen":
        return a.tag === "GREEN HYDROGEN" || /hydrogen|nghm|electrolyzer/i.test(`${a.title} ${a.excerpt}`);
      default:
        return true;
    }
  });
}

export function searchArticles(articles, query) {
  const q = query.trim().toLowerCase();
  if (!q) return articles;
  return articles.filter((a) =>
    [a.title, a.excerpt, a.tag, a.country, a.methodology, a.sourceName]
      .filter(Boolean)
      .some((field) => String(field).toLowerCase().includes(q))
  );
}

export function normalizeArticle(article) {
  return {
    ...article,
    region: article.region || (article.country === "India" || article.tag === "INDIA" ? "india" : "world"),
    accent: article.accent || "#86efac",
    date: formatNewsDate(article.publishedAt),
    // Never substitute fake stock photos — image stays null if unavailable
    image: article.image || null,
  };
}

function readSessionCache() {
  try {
    const raw = sessionStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (Date.now() - parsed.cachedAt > CACHE_TTL_MS) return null;
    return parsed.feed;
  } catch {
    return null;
  }
}

function writeSessionCache(feed) {
  try {
    sessionStorage.setItem(CACHE_KEY, JSON.stringify({ cachedAt: Date.now(), feed }));
  } catch {
    /* ignore */
  }
}

export async function loadNewsFeed({ force = false } = {}) {
  if (!force) {
    const cached = readSessionCache();
    if (cached?.version >= 2) return cached;
  }

  const res = await fetch(`${FEED_URL}?t=${Date.now()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Could not load news feed (${res.status})`);
  const feed = await res.json();
  writeSessionCache(feed);
  return feed;
}
