/**
 * Client-side news feed loader.
 * Reads /news-feed.json (generated by scripts/fetch-news.mjs at build time
 * and refreshed every 6 hours via GitHub Actions).
 */

import { NEWS_PHOTOS } from "../data/media.js";

const FEED_URL = "/news-feed.json";
const CACHE_KEY = "cb_news_feed_v1";
const CACHE_TTL_MS = 30 * 60 * 1000; // 30 min client cache

export const NEWS_FILTERS = [
  { id: "all", label: "All" },
  { id: "verra", label: "Verra" },
  { id: "registry", label: "VCS Registry" },
  { id: "esg", label: "ESG / GHG" },
  { id: "india", label: "India" },
  { id: "green-hydrogen", label: "Green H₂" },
];

export function formatNewsDate(iso) {
  if (!iso) return "";
  try {
    return new Date(iso).toLocaleDateString("en-IN", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch {
    return iso;
  }
}

export function filterArticles(articles, filterId) {
  if (!filterId || filterId === "all") return articles;
  return articles.filter((a) => {
    switch (filterId) {
      case "verra":
        return a.source === "verra" || a.tag === "VERRA";
      case "registry":
        return a.source === "verra-registry" || a.type === "registry";
      case "esg":
        return a.type === "esg" || ["ESG", "CLIMATE", "CARBON MARKET"].includes(a.tag);
      case "india":
        return a.country === "India" || a.tag === "INDIA";
      case "green-hydrogen":
        return a.tag === "GREEN HYDROGEN" || /hydrogen|nghm|electrolyzer/i.test(`${a.title} ${a.excerpt}`);
      default:
        return true;
    }
  });
}

export function searchArticles(articles, query) {
  const q = query.trim().toLowerCase();
  if (!q) return articles;
  return articles.filter((a) =>
    [a.title, a.excerpt, a.tag, a.country, a.methodology, a.sourceName]
      .filter(Boolean)
      .some((field) => String(field).toLowerCase().includes(q))
  );
}

/** Ensure every article has a photo (fallback for older cached feeds). */
export function normalizeArticle(article, index = 0) {
  return {
    ...article,
    image: article.image || NEWS_PHOTOS[index % NEWS_PHOTOS.length],
    accent: article.accent || "#86efac",
    date: formatNewsDate(article.publishedAt),
  };
}

function readSessionCache() {
  try {
    const raw = sessionStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (Date.now() - parsed.cachedAt > CACHE_TTL_MS) return null;
    return parsed.feed;
  } catch {
    return null;
  }
}

function writeSessionCache(feed) {
  try {
    sessionStorage.setItem(CACHE_KEY, JSON.stringify({ cachedAt: Date.now(), feed }));
  } catch {
    /* quota exceeded — ignore */
  }
}

export async function loadNewsFeed({ force = false } = {}) {
  if (!force) {
    const cached = readSessionCache();
    if (cached) return cached;
  }

  const res = await fetch(`${FEED_URL}?t=${Date.now()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Could not load news feed (${res.status})`);
  const feed = await res.json();
  writeSessionCache(feed);
  return feed;
}
